# Generated by Django 4.2.7 on 2023-11-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bolim',
            name='boss',
        ),
        migrations.RemoveField(
            model_name='bolim',
            name='ishchilar_soni',
        ),
        migrations.AddField(
            model_name='bolim',
            name='rasm',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
